[project]
name = "atlas-email"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiosmtplib>=5.1.0",
    "nats-py>=2.14.0",
    "pydantic>=2.13.4",
    "pydantic-settings[yaml]>=2.14.0",
    "uvloop>=0.22.1",
]

[dependency-groups]
dev = [
    "aiosmtpd>=1.4.6",
    "pytest>=9.0.3",
    "pytest-asyncio>=1.3.0",
    "pytest-cov>=7.1.0",
]

[tool.pytest.ini_options]
pythonpath = [".", "src"]
asyncio_mode = "auto"

[tool.ruff.lint]
extend-select = ["I", "RUF"]
ignore = ["RUF001", "RUF002"]

[tool.basedpyright]
include = ["src"]
extraPaths = ["./src"]
typeCheckingMode = "standard"
exclude = [
  "**/__pycache__",
  "**/.venv",
  "**/.pytest_cache",
  "**/build",
  "**/dist",
  "**/migrations",
]
pythonVersion = "3.14"
